/* Generated by MyraPad at 14.12.2024 23:44:29 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace JABEUP_Game.UI.MyraOptions
{
	partial class OptionsLayout: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Options";
			label1.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label2 = new Label();
			label2.Text = "Sound volume:";
			Grid.SetColumn(label2, 1);

			soundVolumeSlider = new HorizontalSlider();
			soundVolumeSlider.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			soundVolumeSlider.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			soundVolumeSlider.Id = "soundVolumeSlider";
			Grid.SetColumn(soundVolumeSlider, 2);

			var label3 = new Label();
			label3.Text = "Music volume:";
			Grid.SetColumn(label3, 1);
			Grid.SetRow(label3, 1);

			musicVolumeSlider = new HorizontalSlider();
			musicVolumeSlider.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			musicVolumeSlider.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			musicVolumeSlider.Id = "musicVolumeSlider";
			Grid.SetColumn(musicVolumeSlider, 2);
			Grid.SetRow(musicVolumeSlider, 1);

			var grid1 = new Grid();
			grid1.RowSpacing = 10;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(soundVolumeSlider);
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(musicVolumeSlider);

			musicSettings = new TabItem();
			musicSettings.Text = "Music";
			musicSettings.Id = "musicSettings";
			musicSettings.Content = grid1;

			var label4 = new Label();
			label4.Text = "Movement:";
			Grid.SetColumn(label4, 1);

			var label5 = new Label();
			label5.Text = "Up:";
			Grid.SetColumn(label5, 1);
			Grid.SetRow(label5, 1);

			var label6 = new Label();
			label6.Text = "W (change)";

			bindChangeButton_Up = new Button();
			bindChangeButton_Up.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			bindChangeButton_Up.Id = "bindChangeButton_Up";
			Grid.SetColumn(bindChangeButton_Up, 2);
			Grid.SetRow(bindChangeButton_Up, 1);
			bindChangeButton_Up.Content = label6;

			var label7 = new Label();
			label7.Text = "Down:";
			Grid.SetColumn(label7, 1);
			Grid.SetRow(label7, 2);

			var label8 = new Label();
			label8.Text = "S (change)";

			bindChangeButton_Down = new Button();
			bindChangeButton_Down.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			bindChangeButton_Down.Id = "bindChangeButton_Down";
			Grid.SetColumn(bindChangeButton_Down, 2);
			Grid.SetRow(bindChangeButton_Down, 2);
			bindChangeButton_Down.Content = label8;

			var label9 = new Label();
			label9.Text = "Left:";
			Grid.SetColumn(label9, 1);
			Grid.SetRow(label9, 3);

			var label10 = new Label();
			label10.Text = "A (change)";

			bindChangeButton_Left = new Button();
			bindChangeButton_Left.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			bindChangeButton_Left.Id = "bindChangeButton_Left";
			Grid.SetColumn(bindChangeButton_Left, 2);
			Grid.SetRow(bindChangeButton_Left, 3);
			bindChangeButton_Left.Content = label10;

			var label11 = new Label();
			label11.Text = "Right:";
			Grid.SetColumn(label11, 1);
			Grid.SetRow(label11, 4);

			var label12 = new Label();
			label12.Text = "D (change)";

			bindChangeButton_Right = new Button();
			bindChangeButton_Right.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			bindChangeButton_Right.Id = "bindChangeButton_Right";
			Grid.SetColumn(bindChangeButton_Right, 2);
			Grid.SetRow(bindChangeButton_Right, 4);
			bindChangeButton_Right.Content = label12;

			var label13 = new Label();
			label13.Text = "Jump:";
			Grid.SetColumn(label13, 1);
			Grid.SetRow(label13, 5);

			var label14 = new Label();
			label14.Text = "Space (change)";

			bindChangeButton_Jump = new Button();
			bindChangeButton_Jump.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			bindChangeButton_Jump.Id = "bindChangeButton_Jump";
			Grid.SetColumn(bindChangeButton_Jump, 2);
			Grid.SetRow(bindChangeButton_Jump, 5);
			bindChangeButton_Jump.Content = label14;

			var label15 = new Label();
			label15.Text = "Actions:";
			Grid.SetColumn(label15, 1);
			Grid.SetRow(label15, 6);

			var label16 = new Label();
			label16.Text = "Attack:";
			Grid.SetColumn(label16, 1);
			Grid.SetRow(label16, 7);

			var label17 = new Label();
			label17.Text = "LCtrl (change)";

			bindChangeButton_Attack = new Button();
			bindChangeButton_Attack.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			bindChangeButton_Attack.Id = "bindChangeButton_Attack";
			Grid.SetColumn(bindChangeButton_Attack, 2);
			Grid.SetRow(bindChangeButton_Attack, 7);
			bindChangeButton_Attack.Content = label17;

			var label18 = new Label();
			label18.Text = "Defend:";
			Grid.SetColumn(label18, 1);
			Grid.SetRow(label18, 8);

			var label19 = new Label();
			label19.Text = "LShift (change)";

			bindChangeButton_Defend = new Button();
			bindChangeButton_Defend.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			bindChangeButton_Defend.Id = "bindChangeButton_Defend";
			Grid.SetColumn(bindChangeButton_Defend, 2);
			Grid.SetRow(bindChangeButton_Defend, 8);
			bindChangeButton_Defend.Content = label19;

			bindChangeButtonsGrid = new Grid();
			bindChangeButtonsGrid.RowSpacing = 10;
			bindChangeButtonsGrid.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			bindChangeButtonsGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			bindChangeButtonsGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			bindChangeButtonsGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			bindChangeButtonsGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			bindChangeButtonsGrid.Id = "bindChangeButtonsGrid";
			bindChangeButtonsGrid.Widgets.Add(label4);
			bindChangeButtonsGrid.Widgets.Add(label5);
			bindChangeButtonsGrid.Widgets.Add(bindChangeButton_Up);
			bindChangeButtonsGrid.Widgets.Add(label7);
			bindChangeButtonsGrid.Widgets.Add(bindChangeButton_Down);
			bindChangeButtonsGrid.Widgets.Add(label9);
			bindChangeButtonsGrid.Widgets.Add(bindChangeButton_Left);
			bindChangeButtonsGrid.Widgets.Add(label11);
			bindChangeButtonsGrid.Widgets.Add(bindChangeButton_Right);
			bindChangeButtonsGrid.Widgets.Add(label13);
			bindChangeButtonsGrid.Widgets.Add(bindChangeButton_Jump);
			bindChangeButtonsGrid.Widgets.Add(label15);
			bindChangeButtonsGrid.Widgets.Add(label16);
			bindChangeButtonsGrid.Widgets.Add(bindChangeButton_Attack);
			bindChangeButtonsGrid.Widgets.Add(label18);
			bindChangeButtonsGrid.Widgets.Add(bindChangeButton_Defend);

			controlSettings = new TabItem();
			controlSettings.Text = "Controls";
			controlSettings.Id = "controlSettings";
			controlSettings.Content = bindChangeButtonsGrid;

			var tabControl1 = new TabControl();
			tabControl1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			tabControl1.Items.Add(musicSettings);
			tabControl1.Items.Add(controlSettings);

			textSaved = new Label();
			textSaved.Text = "Saved!";
			textSaved.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			textSaved.Margin = new Thickness(0, 20, 0, 0);
			textSaved.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textSaved.Visible = false;
			textSaved.Id = "textSaved";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(tabControl1);
			verticalStackPanel1.Widgets.Add(textSaved);

			var label20 = new Label();
			label20.Text = "Back";

			backButton = new Button();
			backButton.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			backButton.Id = "backButton";
			backButton.Content = label20;

			var label21 = new Label();
			label21.Text = "Save";

			saveButton = new Button();
			saveButton.MouseCursor = Myra.Graphics2D.UI.MouseCursorType.Hand;
			saveButton.Id = "saveButton";
			saveButton.Content = label21;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 30;
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			horizontalStackPanel1.Margin = new Thickness(0, 0, 0, 10);
			horizontalStackPanel1.Widgets.Add(backButton);
			horizontalStackPanel1.Widgets.Add(saveButton);

			keyBindWindowText = new Label();
			keyBindWindowText.Text = "Press a keyboard button for {} or Escape to cancel";
			keyBindWindowText.Wrap = true;
			keyBindWindowText.Margin = new Thickness(0, 10);
			keyBindWindowText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			keyBindWindowText.Id = "keyBindWindowText";

			keyBindWindow = new Window();
			keyBindWindow.Title = "Key bind";
			keyBindWindow.DragDirection = Myra.Graphics2D.UI.DragDirection.None;
			keyBindWindow.CloseKey = Microsoft.Xna.Framework.Input.Keys.None;
			keyBindWindow.Left = 433;
			keyBindWindow.Top = 415;
			keyBindWindow.MaxWidth = 600;
			keyBindWindow.Id = "keyBindWindow";
			keyBindWindow.Content = keyBindWindowText;

			
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(horizontalStackPanel1);
			//Widgets.Add(keyBindWindow);
		}

		
		public HorizontalSlider soundVolumeSlider;
		public HorizontalSlider musicVolumeSlider;
		public TabItem musicSettings;
		public Button bindChangeButton_Up;
		public Button bindChangeButton_Down;
		public Button bindChangeButton_Left;
		public Button bindChangeButton_Right;
		public Button bindChangeButton_Jump;
		public Button bindChangeButton_Attack;
		public Button bindChangeButton_Defend;
		public Grid bindChangeButtonsGrid;
		public TabItem controlSettings;
		public Label textSaved;
		public Button backButton;
		public Button saveButton;
		public Label keyBindWindowText;
		public Window keyBindWindow;
	}
}
