/* Generated by MyraPad at 17.12.2024 15:19:20 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace JABEUP_Game.UI.MyraDeathScreen
{
	partial class DeathScreenLayout: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "You are dead";
			label1.TextColor = ColorStorage.CreateColor(254, 57, 48, 255);
			label1.Margin = new Thickness(0, 0, 0, 20);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label1.Scale = new Vector2();

			scoreText = new Label();
			scoreText.Text = "Your score: ";
			scoreText.Margin = new Thickness(0, 0, 0, 10);
			scoreText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			scoreText.Id = "scoreText";

			var label2 = new Label();
			label2.Text = "Respawn";

			respawnButton = new Button();
			respawnButton.Margin = new Thickness(0, 0, 0, 40);
			respawnButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			respawnButton.Id = "respawnButton";
			respawnButton.Content = label2;

			var label3 = new Label();
			label3.Text = "Go to menu";

			menuButton = new Button();
			menuButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			menuButton.Id = "menuButton";
			menuButton.Content = label3;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 10;
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(scoreText);
			verticalStackPanel1.Widgets.Add(respawnButton);
			verticalStackPanel1.Widgets.Add(menuButton);

			
			Background = new SolidBrush("#00000000");
			Widgets.Add(verticalStackPanel1);
		}

		
		public Label scoreText;
		public Button respawnButton;
		public Button menuButton;
	}
}
