/* Generated by MyraPad at 17.12.2024 21:14:50 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace JABEUP_Game.UI.MyraMenu
{
	partial class MenuLayout: Panel
	{
		private void BuildUI()
		{
			pausedText = new Label();
			pausedText.Text = "Paused";
			pausedText.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			pausedText.Margin = new Thickness(0, 30, 0, 0);
			pausedText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			pausedText.Visible = false;
			pausedText.Id = "pausedText";

			var label1 = new Label();
			label1.Text = "JABEUP";
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label2 = new Label();
			label2.Text = "Just Another Beat`Em Up";
			label2.Margin = new Thickness(0, 0, 0, 10);
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var label3 = new Label();
			label3.Text = "Play";

			playButton = new Button();
			playButton.Margin = new Thickness(0, 0, 0, 20);
			playButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			playButton.Id = "playButton";
			playButton.Content = label3;

			var label4 = new Label();
			label4.Text = "Options";

			optionsButton = new Button();
			optionsButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			optionsButton.Id = "optionsButton";
			optionsButton.Content = label4;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 10;
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(label2);
			verticalStackPanel1.Widgets.Add(playButton);
			verticalStackPanel1.Widgets.Add(optionsButton);

			var label5 = new Label();
			label5.Text = "Exit";

			exitButton = new Button();
			exitButton.Margin = new Thickness(0, 0, 0, 10);
			exitButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			exitButton.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			exitButton.Id = "exitButton";
			exitButton.Content = label5;

			authorText = new Label();
			authorText.Text = "authorText";
			authorText.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Right;
			authorText.Margin = new Thickness(0, 0, 15, 15);
			authorText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			authorText.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			authorText.Id = "authorText";

			hiscoreText = new Label();
			hiscoreText.Text = "High score:";
			hiscoreText.Margin = new Thickness(15, 0, 0, 15);
			hiscoreText.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			hiscoreText.Visible = false;
			hiscoreText.Id = "hiscoreText";

			randomText = new Label();
			randomText.Text = "Now in color!";
			randomText.Visible = false;
			randomText.Scale = new Vector2();
			randomText.Rotation = 25;
			randomText.Id = "randomText";

			
			Widgets.Add(pausedText);
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(exitButton);
			Widgets.Add(authorText);
			Widgets.Add(hiscoreText);
			Widgets.Add(randomText);
		}

		
		public Label pausedText;
		public Button playButton;
		public Button optionsButton;
		public Button exitButton;
		public Label authorText;
		public Label hiscoreText;
		public Label randomText;
	}
}
