name: Release

on:
  workflow_dispatch:

env:
  PROJECT_PATH: .

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Setup Wine
      run: |
        sudo apt update
        sudo apt install wine64 p7zip-full curl
        wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/78636f8056fa981584e3a2a3e0f22e2efbc43ef8/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
    - name: Build Windows
      run: dotnet publish ${{ env.PROJECT_PATH }} -r win-x64 -c Release --self-contained --output artifacts/windows
